### ISSUE TITLE
On Mobile - Todo Section not Draggable to maximize or minimise

### ISSUE THREAD

**Issue by heyden** [elnook/notedo#11]
**Describe the bug**

In iPhone Safari, unable to drag the slider to minimize the todo box. Other "draggable" icons are draggable to scale up or down sections.

**To Reproduce**

1. Open a note
2. Attempt to click on the draggable icon between the note and todo section and drag it left/right.

**Expected behavior**

Should be able

**Additional context**

n/a

**Comment by davidwashere** [comment]
The dividers do have a min width/height, with some of the upcoming features those sections will be fully collapsible / collapsed fully by default which will likely fix this issue.

Full disclosure, have not been testing on mobile devices / screen sizes.

**Comment by davidwashere** [comment]
@heyden Its not pretty, but the new buttons for hiding the todos/images should fix this for the time being

Please confirm

**Comment by davidwashere** [comment]
Closing issue, will revisit if necessary when looking at mobile friendly design
