### ISSUE TITLE
New Collection button doesn't work when on homepage

### ISSUE THREAD

**Issue by cmeinco** [elnook/notedo#14]
**Describe the bug**
While on the main landing page, if you click the new collection button, it does nothing.

**To Reproduce**
1. Load up notedo page or click on the big N/otedo to go to the main page
2. click the new collection button
3. nothing happens

**Expected behavior**
New collection button should not be there, or should be implied root and create at the root level.

**Additional context**
N/A

**Comment by davidwashere** [comment]
Fixed in version `0.1.9-1-g5092396`+

Changed so that root is implied, button also didn't do anything when on the 'links' page (essentially anything that wasn't in a collection's context).

**Comment by cmeinco** [comment]
confirmed fixed.
