### ISSUE TITLE
Root Collection Name different

### ISSUE THREAD

**Issue by cmeinco** [elnook/notedo#17]
**Describe the bug**
Same version on two different instances is showing different

**To Reproduce**
1. No Idea.
2. Look at the "Root" node in the collection list, it's different, but as you can see on the version page, they are both up to date.

Could this Possibly because one is an older version?  something off in the db?

**Expected behavior**
Static values should be the same.

**Additional context**
![image](https://user-images.githubusercontent.com/1312111/101861355-765c5480-3b35-11eb-950a-0c1b21910912.png)

**Comment by cmeinco** [comment]
yup, deleted my database and created new one. "Collections" now shows up correctly.   Fine with closing and filing this as database upgrade lessons learned.  no lost data/concerns here that any kind of fix need to be put in.

**Comment by davidwashere** [comment]
The root collection can be named whatever you want, i just changed the default name, upgrading the database will not change the name of the collection. But yes starting fresh will use the 'new' default name...
