### ISSUE TITLE
notedo gui flag doesn't work

### ISSUE THREAD

**Issue by cmeinco** [elnook/notedo#19]
**Describe the bug**
gui command does not serve or open the page correctly

**To Reproduce**
1. `notedo gui`
2. browser opens but does not goto served location
3. and does not serve when manually browsing to host:port

**Expected behavior**
open browser at expected and served location for my ease of usefulness

**Additional context**
Add any other context about the problem here (screenshots, files, etc.)

**Comment by davidwashere** [comment]
Fixed in version `0.1.9-39-g8c20f51` and up
