### ISSUE TITLE
Feedback link opens in current tab (preference request)

### ISSUE THREAD

**Issue by sdg9** [elnook/notedo#2]
**Summary**
This link opens in current tab
![image](https://user-images.githubusercontent.com/3091143/99342654-ff8fac80-2851-11eb-9b6d-d968a43312c2.png)

**Intended Outcome**
New tab please (yes this is just a preference)

**How will it work?**
`target="_blank"` me please

**Comment by davidwashere** [comment]
This should be available in the latest, please confirm

**Comment by davidwashere** [comment]
Closing, change is implemented
