### ISSUE TITLE
Arrow Key Navigation for Screenshots

### ISSUE THREAD

**Issue by heyden** [elnook/notedo#20]
**Summary**

Displaying an image saved to a note brings up a modal. That modal has arrows to navigate the images; if there are multiple. Add arrow key support to navigate images.

**Intended Outcome**

Does not require hand on the mouse.

**How will it work?**

Left and Right arrow keys navigate multiple images on a note.

**Comment by davidwashere** [comment]
Added in [latest pre-release](https://github.com/elnook/notedo/releases/tag/0.1.9-43-g276f535)
